//
//Copyright 2021 The Dapr Authors
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.5
// source: dapr/proto/components/v1/middleware.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequestHeadersCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Uri     string            `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetRequestHeadersCommandResponse) Reset() {
	*x = GetRequestHeadersCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestHeadersCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestHeadersCommandResponse) ProtoMessage() {}

func (x *GetRequestHeadersCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestHeadersCommandResponse.ProtoReflect.Descriptor instead.
func (*GetRequestHeadersCommandResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequestHeadersCommandResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GetRequestHeadersCommandResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *GetRequestHeadersCommandResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type GetResponseHeadersCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetResponseHeadersCommandResponse) Reset() {
	*x = GetResponseHeadersCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponseHeadersCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseHeadersCommandResponse) ProtoMessage() {}

func (x *GetResponseHeadersCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseHeadersCommandResponse.ProtoReflect.Descriptor instead.
func (*GetResponseHeadersCommandResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponseHeadersCommandResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type GetRequestBodyCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetRequestBodyCommandResponse) Reset() {
	*x = GetRequestBodyCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestBodyCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestBodyCommandResponse) ProtoMessage() {}

func (x *GetRequestBodyCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestBodyCommandResponse.ProtoReflect.Descriptor instead.
func (*GetRequestBodyCommandResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequestBodyCommandResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetResponseBodyCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetResponseBodyCommandResponse) Reset() {
	*x = GetResponseBodyCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponseBodyCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseBodyCommandResponse) ProtoMessage() {}

func (x *GetResponseBodyCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseBodyCommandResponse.ProtoReflect.Descriptor instead.
func (*GetResponseBodyCommandResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponseBodyCommandResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetRequestHeadersCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRequestHeadersCommandResponse) Reset() {
	*x = SetRequestHeadersCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRequestHeadersCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequestHeadersCommandResponse) ProtoMessage() {}

func (x *SetRequestHeadersCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequestHeadersCommandResponse.ProtoReflect.Descriptor instead.
func (*SetRequestHeadersCommandResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{4}
}

type SetRequestBodyCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRequestBodyCommandResponse) Reset() {
	*x = SetRequestBodyCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRequestBodyCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequestBodyCommandResponse) ProtoMessage() {}

func (x *SetRequestBodyCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequestBodyCommandResponse.ProtoReflect.Descriptor instead.
func (*SetRequestBodyCommandResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{5}
}

type ExecNextCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExecNextCommandResponse) Reset() {
	*x = ExecNextCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecNextCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecNextCommandResponse) ProtoMessage() {}

func (x *ExecNextCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecNextCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecNextCommandResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{6}
}

type SetResponseStatusCodeCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetResponseStatusCodeCommandResponse) Reset() {
	*x = SetResponseStatusCodeCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetResponseStatusCodeCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponseStatusCodeCommandResponse) ProtoMessage() {}

func (x *SetResponseStatusCodeCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponseStatusCodeCommandResponse.ProtoReflect.Descriptor instead.
func (*SetResponseStatusCodeCommandResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{7}
}

type HandleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*HandleRequest_GetReqHeaders
	//	*HandleRequest_GetReqBody
	//	*HandleRequest_GetRespHeaders
	//	*HandleRequest_SetReqHeaders
	//	*HandleRequest_SetReqBody
	//	*HandleRequest_SetRespBody
	//	*HandleRequest_SetRespStatus
	//	*HandleRequest_GetRespBody
	//	*HandleRequest_ExecNext
	Response isHandleRequest_Response `protobuf_oneof:"response"`
}

func (x *HandleRequest) Reset() {
	*x = HandleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequest) ProtoMessage() {}

func (x *HandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequest.ProtoReflect.Descriptor instead.
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{8}
}

func (m *HandleRequest) GetResponse() isHandleRequest_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *HandleRequest) GetGetReqHeaders() *GetRequestHeadersCommandResponse {
	if x, ok := x.GetResponse().(*HandleRequest_GetReqHeaders); ok {
		return x.GetReqHeaders
	}
	return nil
}

func (x *HandleRequest) GetGetReqBody() *GetRequestBodyCommandResponse {
	if x, ok := x.GetResponse().(*HandleRequest_GetReqBody); ok {
		return x.GetReqBody
	}
	return nil
}

func (x *HandleRequest) GetGetRespHeaders() *GetResponseHeadersCommandResponse {
	if x, ok := x.GetResponse().(*HandleRequest_GetRespHeaders); ok {
		return x.GetRespHeaders
	}
	return nil
}

func (x *HandleRequest) GetSetReqHeaders() *SetRequestHeadersCommandResponse {
	if x, ok := x.GetResponse().(*HandleRequest_SetReqHeaders); ok {
		return x.SetReqHeaders
	}
	return nil
}

func (x *HandleRequest) GetSetReqBody() *SetRequestBodyCommandResponse {
	if x, ok := x.GetResponse().(*HandleRequest_SetReqBody); ok {
		return x.SetReqBody
	}
	return nil
}

func (x *HandleRequest) GetSetRespBody() *SetResponseBodyCommand {
	if x, ok := x.GetResponse().(*HandleRequest_SetRespBody); ok {
		return x.SetRespBody
	}
	return nil
}

func (x *HandleRequest) GetSetRespStatus() *SetResponseStatusCodeCommandResponse {
	if x, ok := x.GetResponse().(*HandleRequest_SetRespStatus); ok {
		return x.SetRespStatus
	}
	return nil
}

func (x *HandleRequest) GetGetRespBody() *GetResponseBodyCommandResponse {
	if x, ok := x.GetResponse().(*HandleRequest_GetRespBody); ok {
		return x.GetRespBody
	}
	return nil
}

func (x *HandleRequest) GetExecNext() *ExecNextCommandResponse {
	if x, ok := x.GetResponse().(*HandleRequest_ExecNext); ok {
		return x.ExecNext
	}
	return nil
}

type isHandleRequest_Response interface {
	isHandleRequest_Response()
}

type HandleRequest_GetReqHeaders struct {
	GetReqHeaders *GetRequestHeadersCommandResponse `protobuf:"bytes,1,opt,name=get_req_headers,json=getReqHeaders,proto3,oneof"`
}

type HandleRequest_GetReqBody struct {
	GetReqBody *GetRequestBodyCommandResponse `protobuf:"bytes,2,opt,name=get_req_body,json=getReqBody,proto3,oneof"`
}

type HandleRequest_GetRespHeaders struct {
	GetRespHeaders *GetResponseHeadersCommandResponse `protobuf:"bytes,3,opt,name=get_resp_headers,json=getRespHeaders,proto3,oneof"`
}

type HandleRequest_SetReqHeaders struct {
	SetReqHeaders *SetRequestHeadersCommandResponse `protobuf:"bytes,4,opt,name=set_req_headers,json=setReqHeaders,proto3,oneof"`
}

type HandleRequest_SetReqBody struct {
	SetReqBody *SetRequestBodyCommandResponse `protobuf:"bytes,5,opt,name=set_req_body,json=setReqBody,proto3,oneof"`
}

type HandleRequest_SetRespBody struct {
	SetRespBody *SetResponseBodyCommand `protobuf:"bytes,6,opt,name=set_resp_body,json=setRespBody,proto3,oneof"`
}

type HandleRequest_SetRespStatus struct {
	SetRespStatus *SetResponseStatusCodeCommandResponse `protobuf:"bytes,7,opt,name=set_resp_status,json=setRespStatus,proto3,oneof"`
}

type HandleRequest_GetRespBody struct {
	GetRespBody *GetResponseBodyCommandResponse `protobuf:"bytes,8,opt,name=get_resp_body,json=getRespBody,proto3,oneof"`
}

type HandleRequest_ExecNext struct {
	ExecNext *ExecNextCommandResponse `protobuf:"bytes,9,opt,name=exec_next,json=execNext,proto3,oneof"`
}

func (*HandleRequest_GetReqHeaders) isHandleRequest_Response() {}

func (*HandleRequest_GetReqBody) isHandleRequest_Response() {}

func (*HandleRequest_GetRespHeaders) isHandleRequest_Response() {}

func (*HandleRequest_SetReqHeaders) isHandleRequest_Response() {}

func (*HandleRequest_SetReqBody) isHandleRequest_Response() {}

func (*HandleRequest_SetRespBody) isHandleRequest_Response() {}

func (*HandleRequest_SetRespStatus) isHandleRequest_Response() {}

func (*HandleRequest_GetRespBody) isHandleRequest_Response() {}

func (*HandleRequest_ExecNext) isHandleRequest_Response() {}

type GetRequestHeadersCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRequestHeadersCommand) Reset() {
	*x = GetRequestHeadersCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestHeadersCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestHeadersCommand) ProtoMessage() {}

func (x *GetRequestHeadersCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestHeadersCommand.ProtoReflect.Descriptor instead.
func (*GetRequestHeadersCommand) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{9}
}

type GetRequestBodyCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRequestBodyCommand) Reset() {
	*x = GetRequestBodyCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestBodyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestBodyCommand) ProtoMessage() {}

func (x *GetRequestBodyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestBodyCommand.ProtoReflect.Descriptor instead.
func (*GetRequestBodyCommand) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{10}
}

type GetResponseHeadersCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetResponseHeadersCommand) Reset() {
	*x = GetResponseHeadersCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponseHeadersCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseHeadersCommand) ProtoMessage() {}

func (x *GetResponseHeadersCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseHeadersCommand.ProtoReflect.Descriptor instead.
func (*GetResponseHeadersCommand) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{11}
}

type GetResponseBodyCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetResponseBodyCommand) Reset() {
	*x = GetResponseBodyCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponseBodyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseBodyCommand) ProtoMessage() {}

func (x *GetResponseBodyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseBodyCommand.ProtoReflect.Descriptor instead.
func (*GetResponseBodyCommand) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{12}
}

type SetRequestHeadersCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Uri     string            `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SetRequestHeadersCommand) Reset() {
	*x = SetRequestHeadersCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRequestHeadersCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequestHeadersCommand) ProtoMessage() {}

func (x *SetRequestHeadersCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequestHeadersCommand.ProtoReflect.Descriptor instead.
func (*SetRequestHeadersCommand) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{13}
}

func (x *SetRequestHeadersCommand) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SetRequestHeadersCommand) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *SetRequestHeadersCommand) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type SetRequestBodyCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetRequestBodyCommand) Reset() {
	*x = SetRequestBodyCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRequestBodyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequestBodyCommand) ProtoMessage() {}

func (x *SetRequestBodyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequestBodyCommand.ProtoReflect.Descriptor instead.
func (*SetRequestBodyCommand) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{14}
}

func (x *SetRequestBodyCommand) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetResponseStatusCodeCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
}

func (x *SetResponseStatusCodeCommand) Reset() {
	*x = SetResponseStatusCodeCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetResponseStatusCodeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponseStatusCodeCommand) ProtoMessage() {}

func (x *SetResponseStatusCodeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponseStatusCodeCommand.ProtoReflect.Descriptor instead.
func (*SetResponseStatusCodeCommand) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{15}
}

func (x *SetResponseStatusCodeCommand) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type SetResponseBodyCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetResponseBodyCommand) Reset() {
	*x = SetResponseBodyCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetResponseBodyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponseBodyCommand) ProtoMessage() {}

func (x *SetResponseBodyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponseBodyCommand.ProtoReflect.Descriptor instead.
func (*SetResponseBodyCommand) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{16}
}

func (x *SetResponseBodyCommand) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecNextCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExecNextCommand) Reset() {
	*x = ExecNextCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecNextCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecNextCommand) ProtoMessage() {}

func (x *ExecNextCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecNextCommand.ProtoReflect.Descriptor instead.
func (*ExecNextCommand) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{17}
}

type HandleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//
	//	*HandleResponse_GetReqHeaders
	//	*HandleResponse_GetReqBody
	//	*HandleResponse_GetRespHeaders
	//	*HandleResponse_SetReqHeaders
	//	*HandleResponse_SetReqBody
	//	*HandleResponse_SetRespBody
	//	*HandleResponse_SetRespStatus
	//	*HandleResponse_GetRespBody
	//	*HandleResponse_ExecNext
	Command isHandleResponse_Command `protobuf_oneof:"command"`
}

func (x *HandleResponse) Reset() {
	*x = HandleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleResponse) ProtoMessage() {}

func (x *HandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_components_v1_middleware_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleResponse.ProtoReflect.Descriptor instead.
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_components_v1_middleware_proto_rawDescGZIP(), []int{18}
}

func (m *HandleResponse) GetCommand() isHandleResponse_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *HandleResponse) GetGetReqHeaders() *GetRequestHeadersCommand {
	if x, ok := x.GetCommand().(*HandleResponse_GetReqHeaders); ok {
		return x.GetReqHeaders
	}
	return nil
}

func (x *HandleResponse) GetGetReqBody() *GetRequestBodyCommand {
	if x, ok := x.GetCommand().(*HandleResponse_GetReqBody); ok {
		return x.GetReqBody
	}
	return nil
}

func (x *HandleResponse) GetGetRespHeaders() *GetResponseHeadersCommand {
	if x, ok := x.GetCommand().(*HandleResponse_GetRespHeaders); ok {
		return x.GetRespHeaders
	}
	return nil
}

func (x *HandleResponse) GetSetReqHeaders() *SetRequestHeadersCommand {
	if x, ok := x.GetCommand().(*HandleResponse_SetReqHeaders); ok {
		return x.SetReqHeaders
	}
	return nil
}

func (x *HandleResponse) GetSetReqBody() *SetRequestBodyCommand {
	if x, ok := x.GetCommand().(*HandleResponse_SetReqBody); ok {
		return x.SetReqBody
	}
	return nil
}

func (x *HandleResponse) GetSetRespBody() *SetResponseBodyCommand {
	if x, ok := x.GetCommand().(*HandleResponse_SetRespBody); ok {
		return x.SetRespBody
	}
	return nil
}

func (x *HandleResponse) GetSetRespStatus() *SetResponseStatusCodeCommand {
	if x, ok := x.GetCommand().(*HandleResponse_SetRespStatus); ok {
		return x.SetRespStatus
	}
	return nil
}

func (x *HandleResponse) GetGetRespBody() *GetResponseBodyCommand {
	if x, ok := x.GetCommand().(*HandleResponse_GetRespBody); ok {
		return x.GetRespBody
	}
	return nil
}

func (x *HandleResponse) GetExecNext() *ExecNextCommand {
	if x, ok := x.GetCommand().(*HandleResponse_ExecNext); ok {
		return x.ExecNext
	}
	return nil
}

type isHandleResponse_Command interface {
	isHandleResponse_Command()
}

type HandleResponse_GetReqHeaders struct {
	GetReqHeaders *GetRequestHeadersCommand `protobuf:"bytes,1,opt,name=get_req_headers,json=getReqHeaders,proto3,oneof"`
}

type HandleResponse_GetReqBody struct {
	GetReqBody *GetRequestBodyCommand `protobuf:"bytes,2,opt,name=get_req_body,json=getReqBody,proto3,oneof"`
}

type HandleResponse_GetRespHeaders struct {
	GetRespHeaders *GetResponseHeadersCommand `protobuf:"bytes,3,opt,name=get_resp_headers,json=getRespHeaders,proto3,oneof"`
}

type HandleResponse_SetReqHeaders struct {
	SetReqHeaders *SetRequestHeadersCommand `protobuf:"bytes,4,opt,name=set_req_headers,json=setReqHeaders,proto3,oneof"`
}

type HandleResponse_SetReqBody struct {
	SetReqBody *SetRequestBodyCommand `protobuf:"bytes,5,opt,name=set_req_body,json=setReqBody,proto3,oneof"`
}

type HandleResponse_SetRespBody struct {
	SetRespBody *SetResponseBodyCommand `protobuf:"bytes,6,opt,name=set_resp_body,json=setRespBody,proto3,oneof"`
}

type HandleResponse_SetRespStatus struct {
	SetRespStatus *SetResponseStatusCodeCommand `protobuf:"bytes,7,opt,name=set_resp_status,json=setRespStatus,proto3,oneof"`
}

type HandleResponse_GetRespBody struct {
	GetRespBody *GetResponseBodyCommand `protobuf:"bytes,8,opt,name=get_resp_body,json=getRespBody,proto3,oneof"`
}

type HandleResponse_ExecNext struct {
	ExecNext *ExecNextCommand `protobuf:"bytes,9,opt,name=exec_next,json=execNext,proto3,oneof"`
}

func (*HandleResponse_GetReqHeaders) isHandleResponse_Command() {}

func (*HandleResponse_GetReqBody) isHandleResponse_Command() {}

func (*HandleResponse_GetRespHeaders) isHandleResponse_Command() {}

func (*HandleResponse_SetReqHeaders) isHandleResponse_Command() {}

func (*HandleResponse_SetReqBody) isHandleResponse_Command() {}

func (*HandleResponse_SetRespBody) isHandleResponse_Command() {}

func (*HandleResponse_SetRespStatus) isHandleResponse_Command() {}

func (*HandleResponse_GetRespBody) isHandleResponse_Command() {}

func (*HandleResponse_ExecNext) isHandleResponse_Command() {}

var File_dapr_proto_components_v1_middleware_proto protoreflect.FileDescriptor

var file_dapr_proto_components_v1_middleware_proto_rawDesc = []byte{
	0x0a, 0x29, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c,
	0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x64, 0x61, 0x70,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x25, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xeb, 0x01, 0x0a, 0x20, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x61, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x47, 0x2e, 0x64, 0x61, 0x70, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xc3, 0x01, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x48,
	0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x33, 0x0a,
	0x1d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x34, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x20, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x0a, 0x1d,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x0a,
	0x17, 0x45, 0x78, 0x65, 0x63, 0x4e, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x24, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0xfe, 0x06, 0x0a, 0x0d, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x64, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x64, 0x61,
	0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x67, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x5b, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x5f,
	0x72, 0x65, 0x71, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37,
	0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x67, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x3b, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e,
	0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x64,
	0x0a, 0x0f, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x12, 0x5b, 0x0a, 0x0c, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x5f,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x64, 0x61, 0x70,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x42, 0x6f, 0x64,
	0x79, 0x12, 0x56, 0x0a, 0x0d, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x68, 0x0a, 0x0f, 0x73, 0x65, 0x74,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x5e, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x64, 0x61, 0x70,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x6f, 0x64, 0x79, 0x12, 0x50, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x63, 0x5f, 0x6e, 0x65, 0x78, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x4e, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78, 0x65,
	0x63, 0x4e, 0x65, 0x78, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x17, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0xdb, 0x01,
	0x0a, 0x18, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x69, 0x12, 0x59, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x1a,
	0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2b, 0x0a, 0x15, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3f, 0x0a, 0x1c, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x2c, 0x0a, 0x16, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x11, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x4e,
	0x65, 0x78, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0xbe, 0x06, 0x0a, 0x0e, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a,
	0x0f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x67, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x53, 0x0a, 0x0c, 0x67,
	0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2f, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x5f, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x64, 0x61, 0x70,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48,
	0x00, 0x52, 0x0e, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x5c, 0x0a, 0x0f, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x64, 0x61, 0x70,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00,
	0x52, 0x0d, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x53, 0x0a, 0x0c, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x56, 0x0a, 0x0d, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x64, 0x61,
	0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52,
	0x0b, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x60, 0x0a, 0x0f,
	0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52,
	0x0d, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x56,
	0x0a, 0x0d, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x48, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x63, 0x5f, 0x6e,
	0x65, 0x78, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x64, 0x61, 0x70, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x4e, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78, 0x65, 0x63, 0x4e, 0x65, 0x78, 0x74,
	0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x32, 0xfa, 0x01, 0x0a, 0x0e,
	0x48, 0x74, 0x74, 0x70, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x12, 0x4b,
	0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x29, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x06, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x27, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x38,
	0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x64, 0x61, 0x70, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dapr_proto_components_v1_middleware_proto_rawDescOnce sync.Once
	file_dapr_proto_components_v1_middleware_proto_rawDescData = file_dapr_proto_components_v1_middleware_proto_rawDesc
)

func file_dapr_proto_components_v1_middleware_proto_rawDescGZIP() []byte {
	file_dapr_proto_components_v1_middleware_proto_rawDescOnce.Do(func() {
		file_dapr_proto_components_v1_middleware_proto_rawDescData = protoimpl.X.CompressGZIP(file_dapr_proto_components_v1_middleware_proto_rawDescData)
	})
	return file_dapr_proto_components_v1_middleware_proto_rawDescData
}

var file_dapr_proto_components_v1_middleware_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_dapr_proto_components_v1_middleware_proto_goTypes = []interface{}{
	(*GetRequestHeadersCommandResponse)(nil),     // 0: dapr.proto.components.v1.GetRequestHeadersCommandResponse
	(*GetResponseHeadersCommandResponse)(nil),    // 1: dapr.proto.components.v1.GetResponseHeadersCommandResponse
	(*GetRequestBodyCommandResponse)(nil),        // 2: dapr.proto.components.v1.GetRequestBodyCommandResponse
	(*GetResponseBodyCommandResponse)(nil),       // 3: dapr.proto.components.v1.GetResponseBodyCommandResponse
	(*SetRequestHeadersCommandResponse)(nil),     // 4: dapr.proto.components.v1.SetRequestHeadersCommandResponse
	(*SetRequestBodyCommandResponse)(nil),        // 5: dapr.proto.components.v1.SetRequestBodyCommandResponse
	(*ExecNextCommandResponse)(nil),              // 6: dapr.proto.components.v1.ExecNextCommandResponse
	(*SetResponseStatusCodeCommandResponse)(nil), // 7: dapr.proto.components.v1.SetResponseStatusCodeCommandResponse
	(*HandleRequest)(nil),                        // 8: dapr.proto.components.v1.HandleRequest
	(*GetRequestHeadersCommand)(nil),             // 9: dapr.proto.components.v1.GetRequestHeadersCommand
	(*GetRequestBodyCommand)(nil),                // 10: dapr.proto.components.v1.GetRequestBodyCommand
	(*GetResponseHeadersCommand)(nil),            // 11: dapr.proto.components.v1.GetResponseHeadersCommand
	(*GetResponseBodyCommand)(nil),               // 12: dapr.proto.components.v1.GetResponseBodyCommand
	(*SetRequestHeadersCommand)(nil),             // 13: dapr.proto.components.v1.SetRequestHeadersCommand
	(*SetRequestBodyCommand)(nil),                // 14: dapr.proto.components.v1.SetRequestBodyCommand
	(*SetResponseStatusCodeCommand)(nil),         // 15: dapr.proto.components.v1.SetResponseStatusCodeCommand
	(*SetResponseBodyCommand)(nil),               // 16: dapr.proto.components.v1.SetResponseBodyCommand
	(*ExecNextCommand)(nil),                      // 17: dapr.proto.components.v1.ExecNextCommand
	(*HandleResponse)(nil),                       // 18: dapr.proto.components.v1.HandleResponse
	nil,                                          // 19: dapr.proto.components.v1.GetRequestHeadersCommandResponse.HeadersEntry
	nil,                                          // 20: dapr.proto.components.v1.GetResponseHeadersCommandResponse.HeadersEntry
	nil,                                          // 21: dapr.proto.components.v1.SetRequestHeadersCommand.HeadersEntry
	(*MetadataRequest)(nil),                      // 22: dapr.proto.components.v1.MetadataRequest
	(*emptypb.Empty)(nil),                        // 23: google.protobuf.Empty
}
var file_dapr_proto_components_v1_middleware_proto_depIdxs = []int32{
	19, // 0: dapr.proto.components.v1.GetRequestHeadersCommandResponse.headers:type_name -> dapr.proto.components.v1.GetRequestHeadersCommandResponse.HeadersEntry
	20, // 1: dapr.proto.components.v1.GetResponseHeadersCommandResponse.headers:type_name -> dapr.proto.components.v1.GetResponseHeadersCommandResponse.HeadersEntry
	0,  // 2: dapr.proto.components.v1.HandleRequest.get_req_headers:type_name -> dapr.proto.components.v1.GetRequestHeadersCommandResponse
	2,  // 3: dapr.proto.components.v1.HandleRequest.get_req_body:type_name -> dapr.proto.components.v1.GetRequestBodyCommandResponse
	1,  // 4: dapr.proto.components.v1.HandleRequest.get_resp_headers:type_name -> dapr.proto.components.v1.GetResponseHeadersCommandResponse
	4,  // 5: dapr.proto.components.v1.HandleRequest.set_req_headers:type_name -> dapr.proto.components.v1.SetRequestHeadersCommandResponse
	5,  // 6: dapr.proto.components.v1.HandleRequest.set_req_body:type_name -> dapr.proto.components.v1.SetRequestBodyCommandResponse
	16, // 7: dapr.proto.components.v1.HandleRequest.set_resp_body:type_name -> dapr.proto.components.v1.SetResponseBodyCommand
	7,  // 8: dapr.proto.components.v1.HandleRequest.set_resp_status:type_name -> dapr.proto.components.v1.SetResponseStatusCodeCommandResponse
	3,  // 9: dapr.proto.components.v1.HandleRequest.get_resp_body:type_name -> dapr.proto.components.v1.GetResponseBodyCommandResponse
	6,  // 10: dapr.proto.components.v1.HandleRequest.exec_next:type_name -> dapr.proto.components.v1.ExecNextCommandResponse
	21, // 11: dapr.proto.components.v1.SetRequestHeadersCommand.headers:type_name -> dapr.proto.components.v1.SetRequestHeadersCommand.HeadersEntry
	9,  // 12: dapr.proto.components.v1.HandleResponse.get_req_headers:type_name -> dapr.proto.components.v1.GetRequestHeadersCommand
	10, // 13: dapr.proto.components.v1.HandleResponse.get_req_body:type_name -> dapr.proto.components.v1.GetRequestBodyCommand
	11, // 14: dapr.proto.components.v1.HandleResponse.get_resp_headers:type_name -> dapr.proto.components.v1.GetResponseHeadersCommand
	13, // 15: dapr.proto.components.v1.HandleResponse.set_req_headers:type_name -> dapr.proto.components.v1.SetRequestHeadersCommand
	14, // 16: dapr.proto.components.v1.HandleResponse.set_req_body:type_name -> dapr.proto.components.v1.SetRequestBodyCommand
	16, // 17: dapr.proto.components.v1.HandleResponse.set_resp_body:type_name -> dapr.proto.components.v1.SetResponseBodyCommand
	15, // 18: dapr.proto.components.v1.HandleResponse.set_resp_status:type_name -> dapr.proto.components.v1.SetResponseStatusCodeCommand
	12, // 19: dapr.proto.components.v1.HandleResponse.get_resp_body:type_name -> dapr.proto.components.v1.GetResponseBodyCommand
	17, // 20: dapr.proto.components.v1.HandleResponse.exec_next:type_name -> dapr.proto.components.v1.ExecNextCommand
	22, // 21: dapr.proto.components.v1.HttpMiddleware.Init:input_type -> dapr.proto.components.v1.MetadataRequest
	8,  // 22: dapr.proto.components.v1.HttpMiddleware.Handle:input_type -> dapr.proto.components.v1.HandleRequest
	23, // 23: dapr.proto.components.v1.HttpMiddleware.Ping:input_type -> google.protobuf.Empty
	23, // 24: dapr.proto.components.v1.HttpMiddleware.Init:output_type -> google.protobuf.Empty
	18, // 25: dapr.proto.components.v1.HttpMiddleware.Handle:output_type -> dapr.proto.components.v1.HandleResponse
	23, // 26: dapr.proto.components.v1.HttpMiddleware.Ping:output_type -> google.protobuf.Empty
	24, // [24:27] is the sub-list for method output_type
	21, // [21:24] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_dapr_proto_components_v1_middleware_proto_init() }
func file_dapr_proto_components_v1_middleware_proto_init() {
	if File_dapr_proto_components_v1_middleware_proto != nil {
		return
	}
	file_dapr_proto_components_v1_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dapr_proto_components_v1_middleware_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestHeadersCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponseHeadersCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestBodyCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponseBodyCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRequestHeadersCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRequestBodyCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecNextCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetResponseStatusCodeCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestHeadersCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestBodyCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponseHeadersCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponseBodyCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRequestHeadersCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRequestBodyCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetResponseStatusCodeCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetResponseBodyCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecNextCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_components_v1_middleware_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dapr_proto_components_v1_middleware_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*HandleRequest_GetReqHeaders)(nil),
		(*HandleRequest_GetReqBody)(nil),
		(*HandleRequest_GetRespHeaders)(nil),
		(*HandleRequest_SetReqHeaders)(nil),
		(*HandleRequest_SetReqBody)(nil),
		(*HandleRequest_SetRespBody)(nil),
		(*HandleRequest_SetRespStatus)(nil),
		(*HandleRequest_GetRespBody)(nil),
		(*HandleRequest_ExecNext)(nil),
	}
	file_dapr_proto_components_v1_middleware_proto_msgTypes[18].OneofWrappers = []interface{}{
		(*HandleResponse_GetReqHeaders)(nil),
		(*HandleResponse_GetReqBody)(nil),
		(*HandleResponse_GetRespHeaders)(nil),
		(*HandleResponse_SetReqHeaders)(nil),
		(*HandleResponse_SetReqBody)(nil),
		(*HandleResponse_SetRespBody)(nil),
		(*HandleResponse_SetRespStatus)(nil),
		(*HandleResponse_GetRespBody)(nil),
		(*HandleResponse_ExecNext)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dapr_proto_components_v1_middleware_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dapr_proto_components_v1_middleware_proto_goTypes,
		DependencyIndexes: file_dapr_proto_components_v1_middleware_proto_depIdxs,
		MessageInfos:      file_dapr_proto_components_v1_middleware_proto_msgTypes,
	}.Build()
	File_dapr_proto_components_v1_middleware_proto = out.File
	file_dapr_proto_components_v1_middleware_proto_rawDesc = nil
	file_dapr_proto_components_v1_middleware_proto_goTypes = nil
	file_dapr_proto_components_v1_middleware_proto_depIdxs = nil
}
